import { PrimaryButton } from "@fluentui/react";
import react from "react";

const Download: React.FC = (props) => {
    const fileType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
    const fileExtension = '.xlsx';
    const csvData = [
        {
            "Tags": "",
            "Id": 13,
            "Title": "Tes notification",
            "Status": "Open",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "m\n        \n    ",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-13 13:27",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-13 13:34",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 12,
            "Title": "Tes bro",
            "Status": "Open",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-13 10:06",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-13 10:06",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "maintenance",
            "Id": 11,
            "Title": "Tes cuy",
            "Status": "Open",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Grady Archie",
            "Assignee Email": "GradyA@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-13 09:53",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-13 09:53",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "maintenance",
            "Id": 10,
            "Title": "Tes",
            "Status": "Open",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Grady Archie",
            "Assignee Email": "GradyA@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-13 09:52",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-13 09:52",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 9,
            "Title": "Review ticket",
            "Status": "Closed",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Alex Wilber",
            "Assignee Email": "AlexW@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-08 20:08",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-08 20:38",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "Fixed",
            "Last Resolution Comment": "<p>Fixed ya bro</p>",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 8,
            "Title": "Tes",
            "Status": "Open",
            "Requestor": "Alex Wilber",
            "Requestor Email": "AlexW@M365B026215.OnMicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-06 19:37",
            "Created By": "Alex Wilber",
            "Last Updated Date Time": "2023-10-06 19:37",
            "Last Updated By": "Alex Wilber",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 7,
            "Title": "Tes bro",
            "Status": "Open",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-06 19:31",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-06 19:31",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 6,
            "Title": "Ticket Review",
            "Status": "d5745ec7-e5da-485a-978a-0858838381a4",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-06 15:47",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-06 15:47",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 5,
            "Title": "Done Ticket ",
            "Status": "d5745ec7-e5da-485a-978a-0858838381a5",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Alex Wilber",
            "Assignee Email": "AlexW@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-04 13:22",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-04 13:22",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 4,
            "Title": "Pending Bos ",
            "Status": "d5745ec7-e5da-485a-978a-0858838381a4",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Alex Wilber",
            "Assignee Email": "AlexW@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-04 13:22",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-04 13:22",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 3,
            "Title": "Pending Ticket",
            "Status": "d5745ec7-e5da-485a-978a-0858838381a4",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "Alex Wilber",
            "Assignee Email": "AlexW@M365B026215.OnMicrosoft.com",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-10-04 13:22",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-04 13:22",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 2,
            "Title": "Ticket 2",
            "Status": "Resolved",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-09-01 15:04",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-10-04 11:53",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "Fixed",
            "Last Resolution Comment": "<p>Tes</p>",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        },
        {
            "Tags": "",
            "Id": 1,
            "Title": "Tes",
            "Status": "Reopened",
            "Requestor": "MOD Administrator",
            "Requestor Email": "admin@M365B026215.onmicrosoft.com",
            "Assignee": "",
            "Assignee Email": "",
            "Description": "",
            "Priority": "",
            "Expected Date": "",
            "Created Date Time": "2023-09-01 13:46",
            "Created By": "MOD Administrator",
            "Last Updated Date Time": "2023-09-01 17:22",
            "Last Updated By": "MOD Administrator",
            "Last Resolution": "",
            "Last Resolution Comment": "<p>Tes</p>",
            "firstResponseTime (min)": "",
            "isFirstResponseTimeSlaBreached": "",
            "resolutionTime (min)": "",
            "isResolutionTimeSlaBreached": ""
        }
    ]
    async function download() {
        const xlsx: any = await import('xlsx');
        const FileSaver = await require('file-saver');
        // const { saveAs } = await require('file-saver');
        // const FileSaver = await import('file-saver');
        const ws: any = xlsx.utils.json_to_sheet(csvData);
        // const ws: any = xlsx.utils.json_to_sheet(csvData, {
        //   header: ["Created Date Time", "Last Updated Date Time"],
        //   dateNF: 'dd MMM yyyy hh:mm'
        // });

        const wb = { Sheets: { 'data': ws }, SheetNames: ['data'] };
        const excelBuffer = xlsx.write(wb, { bookType: 'xlsx', type: 'array' });
        const data = new Blob([excelBuffer], { type: fileType });
        // console.log(saveAs);
        // console.log(FileSaver);

        FileSaver.saveAs(data, "example" + fileExtension);
        // FileSaver.saveAs(data, "example" + fileExtension);
    }

    return (
        <div>
            <PrimaryButton
                text={"Download"}
                onClick={download}
            />
        </div>
    )
}
export default Download;